---
repos:
  - repo: local
    hooks:
      - id: ansible-lint
        name: ansible-lint
        entry: ansible-lint
        files: \.(yaml|yml)$
        language: python
        args: ['--exclude=roles/geerlingguy.mas']
