---

- name: Ask if dock shall be set up
  pause:
    prompt: "Do you want to set up Dock (yes/no)?"
  register: set_up_dock
  delegate_to: localhost

- name: "Ensure 'dockutil' is present"
  homebrew:
    name: "dockutil"
    state: "present"
  when: hostvars['localhost']['set_up_dock']['user_input'] == "yes"

- name: Remove all crap from Dock
  command: dockutil --remove '{{ item }}'
  ignore_errors: true
  with_items: "{{ dockitems_to_remove }}"
  when: hostvars['localhost']['set_up_dock']['user_input'] == "yes"

- name: Check if items in dock exist
  shell: "dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'"
  with_items: "{{ dockitems_to_persist }}"
  when: hostvars['localhost']['set_up_dock']['user_input'] == "yes"

- name: Fix order
  command: "dockutil --move '{{ item.name }}' --position {{ item.pos }}"
  with_items: "{{ dockitems_to_persist }}"
  when: hostvars['localhost']['set_up_dock']['user_input'] == "yes"
