---
- name: Installing Homebrew Packages
  homebrew:
    name: "{{ brew_packages }}"
    state: "present"
    upgrade_all: "{{ upgrade_homebrew_packages }}"

- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: "present"
