---
# - name: Installing Homebrew Packages
#   homebrew:
#     name: "{{ brew_packages }}"
#     state: "present"
#     upgrade_all: "{{ upgrade_homebrew_packages }}"

- name: Installing Homebrew Multimedia Cask Packages
  homebrew_cask:
    name: "{{ brew_cask_multimedia_packages }}"
    state: "present"
